#!/bin/bash

# Markdown Link Check Script
# This script loops through all subdirectories and runs markdown-link-check
# while avoiding 'test' and 'build' directories

set -e  # Exit on any error

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"

# Loop through all subdirectories
# We avoid node modules
for childPath in website/src/*; do
  if [ ! -d "$childPath" ]; then
      continue
  fi
  if [[ "$childPath" =~ (bin|man) ]]; then
      continue
  fi
  echo "$childPath"
  markdown-link-check \
            --config "$SCRIPT_DIR/markdown-lint-config.json" \
            --quiet \
            "$childPath"
done

echo "README main"
markdown-link-check \
            --config "$SCRIPT_DIR/markdown-lint-config.json" \
            --quiet \
            "README.md"

echo "README charts"
markdown-link-check \
            --config "$SCRIPT_DIR/markdown-lint-config.json" \
            --quiet \
            charts/**/README.md

echo "README Site"
markdown-link-check \
            --config "$SCRIPT_DIR/markdown-lint-config.json" \
            --quiet \
            website/README.md
