version: '3'

tasks:
  # Generate the template in the out directory
  tpl:
    cmds:
      - kubee helmet template --out $(basename {{.USER_WORKING_DIR}})
  tpl-debug:
    cmds:
      - kubee --debug helmet template --out $(basename {{.USER_WORKING_DIR}})
  # Restart
  restart:
    cmds:
      - kubee app restart $(basename {{.USER_WORKING_DIR}})
  play:
    cmds:
      - kubee helmet play $(basename {{.USER_WORKING_DIR}})
  # install with debug
  play-debug:
    cmds:
      - kubee --debug helmet play $(basename {{.USER_WORKING_DIR}})
  # recreate the /charts directory
  dep:
    cmds:
      - kubee helmet update-dependencies -f $(basename {{.USER_WORKING_DIR}})
  # recreate the /charts directory
  dep-force:
    cmds:
      - kubee helmet update-dependencies -f $(basename {{.USER_WORKING_DIR}})
  # Generate the values.schema.json
  schema:
    cmds:
      - |
        COMMAND="helm schema --chart-search-root {{.USER_WORKING_DIR}} --helm-docs-compatibility-mode -k additionalProperties"
        # dependency filter is due to this Traefik error
        # FATA[2025-03-11T14:44:41+01:00] Error while parsing comment of key kind: yaml: found character that cannot start any token
        # Error: plugin "schema" exited with error
        DEPENDENCIES_FILTER=$(yq '[.dependencies[].name] | filter(match("kubee-.*")) | join (" ")' {{.USER_WORKING_DIR}}/Chart.yaml)
        if [ "$DEPENDENCIES_FILTER" != "" ]; then
          COMMAND="$COMMAND --dependencies-filter $DEPENDENCIES_FILTER"
        fi;
        echo "Executing: $COMMAND"
        eval "$COMMAND"
  # Generate all README helm-docs for all charts
  schema-all:
    cmds:
      - |
        # We don't use find exec because it will not stop at first error
        # xargs exit 255 is mandatory to stop at first error
        find "{{.TASK_DIR}}/charts" -maxdepth 2 -mindepth 1 -type f  -name "Chart.yaml" | xargs -I {} bash -c 'cd "$(dirname "{}")" && echo "Executing on $PWD" && task schema || exit 255'
  # Generate the current Chart doc
  helm-docs:
    cmds:
      - |
        if [ "{{.USER_WORKING_DIR}}" == "{{.TASK_DIR}}" ]; then
          echo "To generate for all docs, run helm-docs-all"
          exit 1
        fi
        helm-docs --chart-search-root={{.USER_WORKING_DIR}} --template-files={{.TASK_DIR}}/.helm-docs/helm-docs-extra-templates.gohtml --template-files=README.md.gotmpl

  # Generate the .helmdocsignore file at the project root
  helm-docs-ignore:
    cmds:
      - |
        # Create the .helmdocsignore file
        HELM_DOCS_IGNORE="{{.TASK_DIR}}/.helmdocsignore"
        rm "$HELM_DOCS_IGNORE"
        echo "# Ignore charts dependencies directories" >> "$HELM_DOCS_IGNORE"
        echo "# Should be at the root of repo see issue: https://github.com/norwoodj/helm-docs/issues/206" >> "$HELM_DOCS_IGNORE"
        find "charts" -maxdepth 2 -mindepth 1 -type d  -name "charts" >> "$HELM_DOCS_IGNORE"
  helm-docs-all:
    cmds:
      - |
        find "{{.TASK_DIR}}/charts" -maxdepth 2 -mindepth 1 -type f  -name "Chart.yaml"  | xargs -I {} bash -c 'cd "$(dirname "{}")" && task helm-docs || exit 255'
  # Generate all README helm-docs for all charts
  # and the lint
  docs-all:
    cmds:
      - task helm-docs-all
      - task readme
      - task docs-lint

  # Generate the root Readme.md
  readme:
    cmds:
      - |
        OUTPUT_DIR=out/README
        rm -rf "$OUTPUT_DIR"
        mkdir -p "$OUTPUT_DIR"
        cp "Chart.yaml" "$OUTPUT_DIR"
        cp "README.md.gotmpl" "$OUTPUT_DIR"
        touch "$OUTPUT_DIR/values.yaml"
        MODEL_PATH="$OUTPUT_DIR/model.yaml"
        CHARTS_PATH="charts"
        yq '{.name: { "description": .description, "appVersion": .appVersion, "kind": .annotations."chart.kubee/kind" // "na", "status": .annotations."chart.kubee/status" // "na", "engines": (.annotations."chart.kubee/engines" | from_yaml), "deprecated": .annotations.deprecated  // false, "category": .annotations."chart.kubee/category" // "na" }} | . as $item ireduce ({}; . * $item )' $(find "$CHARTS_PATH" -maxdepth 2 -type f  -name "Chart.yaml") > $MODEL_PATH
        # Path argument in helm-docs should be relative to chart-search-root (not absolute ...)
        (cd $OUTPUT_DIR; helm-docs --template-files={{.TASK_DIR}}/.helm-docs/helm-docs-extra-templates.gohtml --template-files=README.md.gotmpl)
        cp "$OUTPUT_DIR/README.md" "README.md"
  # Check the links
  # do check also the url?
  docs-lint:
    cmds:
      - |
        {{.TASKFILE_DIR}}/contrib/markdown-lint
